name: C++ CI Workflow

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Remove broken apt repos [Ubuntu]
      if: contains(matrix.os, 'ubuntu')
      run: for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

    - name: Dependencies [Ubuntu]
      if: contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt install -y cmake libeigen3-dev libmlpack-dev libopencv-dev libpcl-dev libtclap-dev libconfig++-dev

    - name: Dependencies (from source) [Ubuntu]
      if: contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        # bayes-filters-lib
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/robotology/bayes-filters-lib
        cd bayes-filters-lib
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE} ..
        cmake --build . --config ${{ matrix.build_type }} --target install

        # nanoflann
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/jlblancoc/nanoflann
        cd nanoflann
        git checkout 05d9c35d175fbcedd9f1f854ab49d04ae0bc5dbc
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE} -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE} -DNANOFLANN_BUILD_EXAMPLES:BOOL=OFF -DNANOFLANN_BUILD_TESTS:BOOL=OFF ..
        cmake --build . --config ${{ matrix.build_type }} --target install

    - name: Configure CMake [Ubuntu]
      if: contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..

    - name: Build
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{matrix.build_type}}
